[package]
name = "prompty"
version = "0.1.0"
edition = "2021"
authors = ["Jonas Focke <johndoe@example.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
chrono = "0.4.23"